Pawn promotion
jacobrs/stocklion pull request #26
Opened 2018-02-27 18:55 UTC by yshrdbrn

I handled the pawn promotion when we get it as a PGN.
For handling it on our side though, it needs the AI to be there.
I had class on Monday so I couldn't come to the coding night session so I don't know if you guys talked about it or not, but we should discuss the structure of it.

2018-02-28 15:50 UTC, benrs commented on converters/PGNConverter.cpp
> +    if (std::regex_search(algebraicString, sm, pawnPromotionRegEx))
This will never be reached, PAWN_MOVE already checks for `(=[NBQR])?` in it's regex

2018-02-28 15:50 UTC, benrs commented on converters/PGNConverter.cpp
> +    if (std::regex_search(algebraicString, sm, pawnPromotionRegEx))
You can do another regex under PAWN_MOVE to check if it's promoted and if it is then you can call you promotion function after the move.

2018-03-05 05:20 UTC, yshrdbrn commented
I fixed the error Ben mentioned by moving the pawnPromotion code above the pawnMove

2018-03-05 14:27 UTC, jacobrs commented
This PR does not include the Pawn promotion as part of the possibleMoves function right? That is something we might want to add as part of this PR.

2018-03-06 23:04 UTC, yshrdbrn commented
Yeah, the problem is that the structure of possibleMoves can't handle the promotion right now since it only has the final destination for each piece. We need to define how the AI works in order to know how to define the possibleMoves.

2018-03-07 01:31 UTC, benrs commented on converters/PGNConverter.cpp
> +    if (moveType != PAWN_PROMOTION && !board->movePiece(startingPosition, endingPosition, currPlayer)) {
Not sure if this really feels intuitive. I feel like movePiece should potentially be able to handle the promotion of a pawn, that way we don't need this special case for 'PAWN_PROMOTION' and we simply move the piece like normal + pass in an extra parameter letting the move know what promotion value we want.

2018-03-07 01:31 UTC, benrs commented on converters/PGNConverter.cpp
> +    if (moveType != PAWN_PROMOTION && !board->movePiece(startingPosition, endingPosition, currPlayer)) {
Let me know if you have any criticisms about this method of tackling the problem.

2018-03-07 01:33 UTC, benrs commented on converters/PGNConverter.cpp
> +    if (moveType != PAWN_PROMOTION && !board->movePiece(startingPosition, endingPosition, currPlayer)) {
Or even create a proxy method movePieceAndPromote.

2018-03-08 02:03 UTC, jacobrs commented
We will need to refactor the PossibleMoves function to include those special moves such as promotions, castling and en-passant. Also tests should be writeable if this issue is to be merged since there is no way to use the code currently.

2018-03-08 02:05 UTC, jacobrs requested changes
We need to discuss refactoring possibleMoves.

2020-06-21 02:28 UTC, closed without merging